# Generated by Django 4.1.6 on 2023-02-05 08:47

import databases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.CharField(default=databases.models.generate_uuid, max_length=42, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'loginlog',
                'verbose_name_plural': 'loginlogs',
                'db_table': 'log_login',
            },
        ),
    ]
