# Generated by Django 4.1.6 on 2023-02-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='mode_of_login',
            field=models.CharField(choices=[('browser', 'browser'), ('cli', 'cli')], default='browser', max_length=100),
        ),
    ]
