# Generated by Django 4.1.6 on 2023-02-05 13:58

import databases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_loginlog_mode_of_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=databases.models.generate_uuid, primary_key=True, serialize=False)),
                ('organisation', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='ClientAdmin',
            fields=[
                ('id', models.UUIDField(default=databases.models.generate_uuid, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'ClientAdmin',
                'verbose_name_plural': 'ClientAdmins',
            },
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='id',
            field=models.UUIDField(default=databases.models.generate_uuid, primary_key=True, serialize=False),
        ),
    ]
