# Generated by Django 4.1.6 on 2023-02-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0003_loginlog_user_alter_client_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
