# Generated by Django 4.1.6 on 2023-02-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0004_alter_loginlog_options_clientadmin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mobile',
            field=models.CharField(default=9999999999, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientadmin',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='databases.client'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='clientadmin',
            table='client_admin',
        ),
    ]
