# Generated by Django 4.1.6 on 2023-02-09 14:25

import databases.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0005_surfaceuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurfaceUserAuthLog',
            fields=[
                ('auth_id', models.CharField(default=databases.models.generate_uuid, max_length=42, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('valid_till', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.surfaceuser')),
            ],
        ),
    ]
