# Generated by Django 4.1.6 on 2023-02-06 07:03

import databases.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0006_client_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.CharField(default=databases.models.generate_uuid, max_length=42, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.client', unique=True)),
            ],
            options={
                'verbose_name': 'Quota',
                'verbose_name_plural': 'Quotass',
                'db_table': 'quotas',
            },
        ),
    ]
