# Generated by Django 4.1.6 on 2023-02-10 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0007_apikeys_rename_auth_id_surfaceuserauthlog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeys',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='databases.client'),
            preserve_default=False,
        ),
    ]
