# Generated by Django 4.1.6 on 2023-02-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0009_alter_quota_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quota',
            options={'verbose_name': 'Quota', 'verbose_name_plural': 'Quotas'},
        ),
        migrations.AddField(
            model_name='clientadmin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
