# Generated by Django 4.1.6 on 2023-03-05 05:29

import databases.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0009_apikeys_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="client_verification_token",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=databases.models.generate_uuid,
                        max_length=42,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=databases.models.generate_verification_token,
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databases.client",
                    ),
                ),
            ],
        ),
    ]
