# Generated by Django 4.1.6 on 2023-03-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0010_client_verification_token"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="client_verification_token", new_name="ClientVerificationToken",
        ),
    ]
