# Generated by Django 4.1.6 on 2023-03-06 18:42

import databases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0011_rename_client_verification_token_clientverificationtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=databases.models.generate_uuid,
                        max_length=42,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.CharField(max_length=32)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
