# Generated by Django 4.1.7 on 2023-03-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0012_requestlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlog",
            name="method",
            field=models.CharField(default="", max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requestlog",
            name="path",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
