# Generated by Django 4.1.7 on 2023-03-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0014_alter_requestlog_options_alter_requestlog_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestlog",
            name="user",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
