# Generated by Django 4.1.7 on 2023-03-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0015_requestlog_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="quota",
            name="mail",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
