# Generated by Django 4.1.7 on 2023-03-10 16:45

import databases.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0017_rechargerate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentsLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=databases.models.generate_uuid,
                        max_length=42,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payment_id", models.CharField(max_length=100, unique=True)),
                ("order_id", models.CharField(max_length=100, unique=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="databases.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Log",
                "verbose_name_plural": "Payment Logs",
                "db_table": "payment_log",
            },
        ),
    ]
