# Generated by Django 4.1.7 on 2023-03-10 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0018_paymentslog"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentslog",
            name="amount",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentslog",
            name="rate",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="databases.rechargerate",
            ),
            preserve_default=False,
        ),
    ]
