# Generated by Django 4.1.7 on 2023-03-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0019_paymentslog_amount_paymentslog_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surfaceuser",
            name="username",
            field=models.CharField(default="user", max_length=64, unique=True),
        ),
    ]
