# Generated by Django 4.1.7 on 2023-03-12 20:59

import databases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("databases", "0020_alter_surfaceuser_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogApiRequests",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=databases.models.generate_uuid,
                        max_length=42,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key_used", models.CharField(max_length=100)),
                ("ip_address", models.CharField(max_length=32)),
                ("path", models.CharField(max_length=1000)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("method", models.CharField(max_length=8)),
            ],
            options={
                "verbose_name": "API Request Log",
                "verbose_name_plural": "API Request Logs",
                "db_table": "api_request_log",
            },
        ),
    ]
